import { NextRequest, NextResponse } from 'next/server'
import type { Signal } from '@/lib/types'

const MOCK_SIGNALS: Signal[] = [
  {
    id: 'sig-001',
    signal_type: 'new_business',
    title: 'New Business Registered — Sandton',
    description: 'XYZ Holdings PTY LTD registered at CIPC. Construction sector. Likely needs fleet vehicles for site managers.',
    person_name: 'Thabo Molefe',
    person_phone: '+27 82 445 9901',
    person_email: 'thabo@xyzholdings.co.za',
    person_linkedin: null,
    company_name: 'XYZ Holdings PTY LTD',
    area: 'Sandton',
    city: 'Johannesburg',
    province: 'Gauteng',
    data_source: 'cipc_new_registrations',
    source_url: 'https://eservices.cipc.co.za',
    signal_strength: 'strong',
    buying_probability: 72,
    estimated_budget_min: 350000,
    estimated_budget_max: 600000,
    vehicle_type_likely: 'bakkie',
    converted_to_lead_id: null,
    is_processed: false,
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: 'sig-002',
    signal_type: 'job_change',
    title: 'Senior Director Started at McKinsey — Sandton',
    description: 'Nomsa Dlamini announced new role as Senior Director at McKinsey & Company Johannesburg office on LinkedIn.',
    person_name: 'Nomsa Dlamini',
    person_phone: null,
    person_email: null,
    person_linkedin: 'linkedin.com/in/nomsadlamini',
    company_name: 'McKinsey & Company',
    area: 'Sandton',
    city: 'Johannesburg',
    province: 'Gauteng',
    data_source: 'linkedin_job_changes',
    source_url: 'https://linkedin.com/in/nomsadlamini',
    signal_strength: 'strong',
    buying_probability: 65,
    estimated_budget_min: 600000,
    estimated_budget_max: 1200000,
    vehicle_type_likely: 'suv',
    converted_to_lead_id: null,
    is_processed: false,
    created_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  {
    id: 'sig-003',
    signal_type: 'expat_arrival',
    title: 'UK Expat Relocating to Johannesburg',
    description: 'James Whitfield posted on InterNations forum: "Moving to JHB in April, need a reliable SUV for the family. Any dealer recommendations?"',
    person_name: 'James Whitfield',
    person_phone: null,
    person_email: 'j.whitfield@gmail.com',
    person_linkedin: null,
    company_name: null,
    area: 'Bryanston',
    city: 'Johannesburg',
    province: 'Gauteng',
    data_source: 'internations_forum',
    source_url: 'https://internations.org/johannesburg-expats',
    signal_strength: 'strong',
    buying_probability: 82,
    estimated_budget_min: 500000,
    estimated_budget_max: 900000,
    vehicle_type_likely: 'suv',
    converted_to_lead_id: null,
    is_processed: false,
    created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
  {
    id: 'sig-004',
    signal_type: 'new_driver_age',
    title: 'Teenager Turning 18 — Waterkloof',
    description: "Kagiso Modise's son turning 18 in May. Father is MD at Deloitte Pretoria. High likelihood of first-car purchase.",
    person_name: 'Kagiso Modise',
    person_phone: '+27 83 221 5567',
    person_email: null,
    person_linkedin: 'linkedin.com/in/kagisomodise',
    company_name: 'Deloitte',
    area: 'Waterkloof',
    city: 'Pretoria',
    province: 'Gauteng',
    data_source: 'social_birthday_tracking',
    source_url: null,
    signal_strength: 'strong',
    buying_probability: 70,
    estimated_budget_min: 200000,
    estimated_budget_max: 450000,
    vehicle_type_likely: 'hatch',
    converted_to_lead_id: null,
    is_processed: false,
    created_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
  },
  {
    id: 'sig-005',
    signal_type: 'funding_round',
    title: 'SweepSouth Raises R120M Series C — Rosebank',
    description: 'SweepSouth announced R120 million Series C funding. Expanding fleet operations across Gauteng. CEO Aisha Pandor likely upgrading exec fleet.',
    person_name: 'Aisha Pandor',
    person_phone: null,
    person_email: null,
    person_linkedin: 'linkedin.com/in/aishapandor',
    company_name: 'SweepSouth',
    area: 'Rosebank',
    city: 'Johannesburg',
    province: 'Gauteng',
    data_source: 'techcrunch_sa',
    source_url: 'https://techcrunch.com/sweepsouth-series-c',
    signal_strength: 'strong',
    buying_probability: 68,
    estimated_budget_min: 400000,
    estimated_budget_max: 800000,
    vehicle_type_likely: 'suv',
    converted_to_lead_id: null,
    is_processed: false,
    created_at: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
  },
  {
    id: 'sig-006',
    signal_type: 'housing_development',
    title: 'New Estate: Steyn City Phase 4 — Midrand',
    description: '120 new luxury plots released at Steyn City Phase 4. Average buyer profile: R2M+ income, likely upgrading vehicles to match lifestyle.',
    person_name: null,
    person_phone: null,
    person_email: null,
    person_linkedin: null,
    company_name: 'Steyn City Properties',
    area: 'Midrand',
    city: 'Johannesburg',
    province: 'Gauteng',
    data_source: 'property_24_scraper',
    source_url: 'https://property24.com/steyn-city-phase-4',
    signal_strength: 'medium',
    buying_probability: 52,
    estimated_budget_min: 700000,
    estimated_budget_max: 2000000,
    vehicle_type_likely: 'suv',
    converted_to_lead_id: null,
    is_processed: false,
    created_at: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
  },
  {
    id: 'sig-007',
    signal_type: 'birthday_milestone',
    title: '50th Birthday — Lindiwe Mazibuko, Sandton',
    description: 'Lindiwe Mazibuko celebrating 50th birthday. CFO at Standard Bank. High net worth individual — self-reward vehicle purchase likely.',
    person_name: 'Lindiwe Mazibuko',
    person_phone: '+27 84 332 8876',
    person_email: null,
    person_linkedin: 'linkedin.com/in/lindiwemazibuko',
    company_name: 'Standard Bank',
    area: 'Sandton',
    city: 'Johannesburg',
    province: 'Gauteng',
    data_source: 'linkedin_birthday_alerts',
    source_url: null,
    signal_strength: 'medium',
    buying_probability: 45,
    estimated_budget_min: 800000,
    estimated_budget_max: 1500000,
    vehicle_type_likely: 'sedan',
    converted_to_lead_id: null,
    is_processed: false,
    created_at: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
  },
  {
    id: 'sig-008',
    signal_type: 'wedding',
    title: 'Wedding Announcement — Centurion',
    description: 'Pieter van der Merwe and Zanele Nkosi wedding announcement on Facebook. Both professionals in Centurion — second vehicle likely.',
    person_name: 'Pieter van der Merwe',
    person_phone: null,
    person_email: 'pieter.vdm@outlook.com',
    person_linkedin: null,
    company_name: null,
    area: 'Centurion',
    city: 'Pretoria',
    province: 'Gauteng',
    data_source: 'facebook_life_events',
    source_url: null,
    signal_strength: 'medium',
    buying_probability: 50,
    estimated_budget_min: 250000,
    estimated_budget_max: 500000,
    vehicle_type_likely: 'sedan',
    converted_to_lead_id: null,
    is_processed: false,
    created_at: new Date(Date.now() - 1000 * 60 * 420).toISOString(),
  },
  {
    id: 'sig-009',
    signal_type: 'hiring',
    title: 'Fleet Manager Role — Bidvest Logistics',
    description: 'Bidvest Logistics posting for Fleet Manager in Johannesburg. New fleet manager = fleet review and potential refresh of 50+ vehicles.',
    person_name: null,
    person_phone: null,
    person_email: null,
    person_linkedin: null,
    company_name: 'Bidvest Logistics',
    area: 'Midrand',
    city: 'Johannesburg',
    province: 'Gauteng',
    data_source: 'linkedin_job_postings',
    source_url: 'https://linkedin.com/jobs/bidvest-fleet-manager',
    signal_strength: 'medium',
    buying_probability: 42,
    estimated_budget_min: 5000000,
    estimated_budget_max: 15000000,
    vehicle_type_likely: 'van',
    converted_to_lead_id: null,
    is_processed: false,
    created_at: new Date(Date.now() - 1000 * 60 * 480).toISOString(),
  },
  {
    id: 'sig-010',
    signal_type: 'lease_expiring',
    title: 'BMW Lease Expiring — Fourways',
    description: 'Sipho Mthembu 36-month BMW X3 lease expiring in April 2026. Finance company data indicates no renewal filed yet.',
    person_name: 'Sipho Mthembu',
    person_phone: '+27 79 445 2201',
    person_email: 'sipho.m@gmail.com',
    person_linkedin: null,
    company_name: null,
    area: 'Fourways',
    city: 'Johannesburg',
    province: 'Gauteng',
    data_source: 'lease_expiry_tracker',
    source_url: null,
    signal_strength: 'strong',
    buying_probability: 85,
    estimated_budget_min: 600000,
    estimated_budget_max: 900000,
    vehicle_type_likely: 'suv',
    converted_to_lead_id: null,
    is_processed: false,
    created_at: new Date(Date.now() - 1000 * 60 * 540).toISOString(),
  },
  {
    id: 'sig-011',
    signal_type: 'insurance_claim',
    title: 'Vehicle Write-Off Claim — Kempton Park',
    description: 'Discovery Insure processed a write-off claim for a 2023 Hyundai Tucson. Owner needs replacement vehicle urgently.',
    person_name: 'Refilwe Khumalo',
    person_phone: '+27 81 990 3345',
    person_email: null,
    person_linkedin: null,
    company_name: null,
    area: 'Kempton Park',
    city: 'Johannesburg',
    province: 'Gauteng',
    data_source: 'insurance_claims_feed',
    source_url: null,
    signal_strength: 'strong',
    buying_probability: 72,
    estimated_budget_min: 350000,
    estimated_budget_max: 550000,
    vehicle_type_likely: 'suv',
    converted_to_lead_id: null,
    is_processed: false,
    created_at: new Date(Date.now() - 1000 * 60 * 600).toISOString(),
  },
  {
    id: 'sig-012',
    signal_type: 'promotion',
    title: 'Promoted to VP at Accenture — Rosebank',
    description: 'Priya Naicker promoted to Vice President at Accenture South Africa. LinkedIn announcement received 500+ reactions.',
    person_name: 'Priya Naicker',
    person_phone: null,
    person_email: null,
    person_linkedin: 'linkedin.com/in/priyanaicker',
    company_name: 'Accenture',
    area: 'Rosebank',
    city: 'Johannesburg',
    province: 'Gauteng',
    data_source: 'linkedin_promotions',
    source_url: 'https://linkedin.com/in/priyanaicker',
    signal_strength: 'strong',
    buying_probability: 65,
    estimated_budget_min: 700000,
    estimated_budget_max: 1200000,
    vehicle_type_likely: 'sedan',
    converted_to_lead_id: null,
    is_processed: false,
    created_at: new Date(Date.now() - 1000 * 60 * 660).toISOString(),
  },
  {
    id: 'sig-013',
    signal_type: 'relocation',
    title: 'Family Relocating from Durban to Pretoria',
    description: 'Anton Joubert relocating family to Pretoria for new role at CSIR. Posted in "Moving to Pretoria" Facebook group asking about areas and transport.',
    person_name: 'Anton Joubert',
    person_phone: null,
    person_email: 'anton.joubert@proton.me',
    person_linkedin: null,
    company_name: 'CSIR',
    area: 'Lynnwood',
    city: 'Pretoria',
    province: 'Gauteng',
    data_source: 'facebook_groups',
    source_url: null,
    signal_strength: 'strong',
    buying_probability: 75,
    estimated_budget_min: 300000,
    estimated_budget_max: 600000,
    vehicle_type_likely: 'suv',
    converted_to_lead_id: null,
    is_processed: false,
    created_at: new Date(Date.now() - 1000 * 60 * 720).toISOString(),
  },
  {
    id: 'sig-014',
    signal_type: 'fleet_expansion',
    title: 'Takealot Expanding Last-Mile Fleet — Midstream',
    description: 'Takealot advertising for 30 delivery drivers in Gauteng. Fleet expansion confirmed — sourcing commercial vehicles.',
    person_name: null,
    person_phone: null,
    person_email: null,
    person_linkedin: null,
    company_name: 'Takealot',
    area: 'Midstream',
    city: 'Johannesburg',
    province: 'Gauteng',
    data_source: 'job_board_scraper',
    source_url: 'https://careers.takealot.com',
    signal_strength: 'strong',
    buying_probability: 80,
    estimated_budget_min: 8000000,
    estimated_budget_max: 12000000,
    vehicle_type_likely: 'van',
    converted_to_lead_id: null,
    is_processed: false,
    created_at: new Date(Date.now() - 1000 * 60 * 780).toISOString(),
  },
  {
    id: 'sig-015',
    signal_type: 'competitor_closing',
    title: 'Imperial Auto Centurion Closing Down',
    description: 'Imperial Auto Centurion announced closure. 800+ active customers will need a new dealership for service and future purchases.',
    person_name: null,
    person_phone: null,
    person_email: null,
    person_linkedin: null,
    company_name: 'Imperial Auto',
    area: 'Centurion',
    city: 'Pretoria',
    province: 'Gauteng',
    data_source: 'industry_news',
    source_url: 'https://autotrader.co.za/news/imperial-centurion-closing',
    signal_strength: 'medium',
    buying_probability: 60,
    estimated_budget_min: null,
    estimated_budget_max: null,
    vehicle_type_likely: null,
    converted_to_lead_id: null,
    is_processed: false,
    created_at: new Date(Date.now() - 1000 * 60 * 840).toISOString(),
  },
]

export async function GET(request: NextRequest) {
  const { searchParams } = request.nextUrl
  const type = searchParams.get('type')
  const strength = searchParams.get('strength')
  const area = searchParams.get('area')
  const limit = parseInt(searchParams.get('limit') ?? '50')
  const offset = parseInt(searchParams.get('offset') ?? '0')

  try {
    const { createClient } = await import('@/lib/supabase/server')
    const supabase = await createClient()

    let query = supabase.from('va_signals').select('*', { count: 'exact' })

    if (type) query = query.eq('signal_type', type)
    if (strength) query = query.eq('signal_strength', strength)
    if (area) query = query.ilike('area', `%${area}%`)

    query = query.order('created_at', { ascending: false }).range(offset, offset + limit - 1)

    const { data, error, count } = await query

    if (error) throw error

    return NextResponse.json({ signals: data, total: count })
  } catch {
    // Fallback to mock data
    let filtered = [...MOCK_SIGNALS]
    if (type) filtered = filtered.filter((s) => s.signal_type === type)
    if (strength) filtered = filtered.filter((s) => s.signal_strength === strength)
    if (area) filtered = filtered.filter((s) => s.area?.toLowerCase().includes(area.toLowerCase()))

    const total = filtered.length
    const signals = filtered.slice(offset, offset + limit)

    return NextResponse.json({ signals, total })
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()

    const { createClient } = await import('@/lib/supabase/server')
    const supabase = await createClient()

    const { data, error } = await supabase.from('va_signals').insert(body).select().single()

    if (error) throw error

    return NextResponse.json(data, { status: 201 })
  } catch {
    return NextResponse.json({ error: 'Failed to create signal' }, { status: 500 })
  }
}
